version: "3"
services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank-db
    networks:
      - reactive-bank-mysql

  reactive-bank:
    image: reactive-bank
    networks:
      - reactive-bank-mysql
    depends_on:
      - mysqldb
    ports:
      - "8081:8081"
    restart: always

#Docker Networks
networks:
  reactive-bank-mysql:
